# Generated by Django 2.2.5 on 2019-09-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.BooleanField(default=False),
        ),
    ]
