# Generated by Django 2.2.5 on 2019-10-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
