# Generated by Django 2.2.5 on 2019-10-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191020_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
